### ISSUE TITLE
Empty data folder when running the 7_denoising module

### ISSUE THREAD

**Issue by KarolineBruunDegn** [DominikBuchner/apscale#22] opened 2024-12-16 10:25 UTC
Hello,

I am experiencing an issue with the denoising module in Apscale 2.1.0. After running the module, the output folder (7_denoising/data) remains empty, but the log file and the Project_report_Anholt_Apscale_Analysis.xlsx indicate that the module has completed successfully.

1. I run the denoising with the following command;

apscale --denoising

[kardeg@g-12-l0002 Anholt_Apscale_Analysis_apscale]$ apscale --denoising
10:50:22: Starting individual denoising and chimera removal.
10:50:24: NTC7_FINAL_dereplicated_ESVs_with_chimeras.fasta.gz: Denoised 0 unique sequences into 0 ESVs.
10:50:24: NTC7_FINAL_dereplicated_ESVs_no_chimeras: 0 chimeras removed from 0 ESV sequences.
10:50:24: 12A_FINAL_dereplicated_ESVs_with_chimeras.fasta.gz: Denoised 61608 unique sequences into 50 ESVs.
10:50:24: 12A_FINAL_dereplicated_ESVs_no_chimeras: 0 chimeras removed from 50 ESV sequences.
10:50:24: 13B_FINAL_dereplicated_ESVs_with_chimeras.fasta.gz: Denoised 66194 unique sequences into 66 ESVs.
10:50:24: 13B_FINAL_dereplicated_ESVs_no_chimeras: 2 chimeras removed from 66 ESV sequences.
continues..

10:50:30: Constructing final ESV fasta files.
10:50:30: NTC7_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 12A_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 13B_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 13A_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 3C_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 8A_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: 6C_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: S1_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
10:50:30: NTC1_FINAL_dereplicated_ESVs_no_chimeras: Successfully denoised and hashed.
continues..

2. The log file suggests that all steps were completed successfully, and the "Project_report_Anholt_Apscale_Analysis.xlsx" reflects that the process finished without issues.

<img width="657" alt="denoising_logfile" src="https://github.com/user-attachments/assets/1ccc2f1d-3457-4706-b060-3f3081e03013" />
<img width="684" alt="denoising_project_report" src="https://github.com/user-attachments/assets/1e254b73-5e21-423c-8be1-6cfd12185f33" />

3. However, when I navigate to the output folder (7_denoising/data), it is empty:

ls -lh 7_denoising/data

[kardeg@g-12-l0002 Anholt_Apscale_Analysis_apscale]$ ls -lh 7_denoising/data/
total 0

4. I also tried searching for the output files using the find command:
   find /home/projects/dp_00007/people/kardeg -name "*FINAL_dereplicated_ESVs_no_chimeras*"

No files are found anywhere on the system.

I hope you can help me :-) 

Best,
Karoline Degn

**Comment by DominikBuchner** [comment] 2024-12-16 10:33
Can you upload apscale project somewhere, so I can take a look? This is strange and not intended behaviour.

**Comment by KarolineBruunDegn** [comment] 2024-12-16 10:49
Yes I will send it to your mail through WeTransfer

**Comment by DominikBuchner** [comment] 2024-12-16 16:41
Hi Karoline,
fixed with 2.1.1.
best
Dominik

**Closed by DominikBuchner** 2024-12-16 16:41 UTC

**Comment by KarolineBruunDegn** [comment] 2024-12-17 08:49
Thank you :)

**Comment by KarolineBruunDegn** [comment] 2024-12-17 10:43
Hi Dominik. 
Thank you for your support :) Module 7 is working now. However, just to let you know, the output files in the module 7 data folder do no longer have the "_dereplicated_ESV_no_chimeras" suffix. But I guess that is no problem.
Best,
Karoline

**Comment by KarolineBruunDegn** [comment] 2024-12-17 10:43
<img width="651" alt="image" src="https://github.com/user-attachments/assets/1e7057a3-e755-4856-9551-4870e0fff611" />

**Comment by DominikBuchner** [comment] 2024-12-17 10:59
This is intended as well, since this is your sample input name :) Unless you want an esv table with all those appendices :D

**Comment by KarolineBruunDegn** [comment] 2024-12-17 12:09
Ahh, yes I see :D That you very much for your help!
