### ISSUE TITLE
bug: analyses and/or installation not working in some pc conditions

### ISSUE THREAD

**Issue by OndroV** [DominikBuchner/apscale#6] opened 2022-09-10 17:34 UTC
Hi Dominik,

today I finally tried to set up apscale, but it just mysteriously doesnt work for me. Can you see any solution to [this issue described at apscale_gui](https://github.com/TillMacher/apscale_gui/issues/1), please?

Cheers,
Ondrej

**Comment by DominikBuchner** [comment] 2022-09-10 17:53
Can you please upload the files you try to analyse as well as the exact output when apscale breaks down?

**Comment by OndroV** [comment] 2022-09-10 17:58
Sure,
with [these files](https://github.com/TillMacher/apscale_gui/tree/master/_tutorial_data) from TIll I get the following output:
`
19:19:26: Finding all file pairs in your input. This may take a while.
19:19:26: Found 3 matching file pairs in 6 input files.
19:19:26: Starting to merge forward and reverse reads.
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 436, in _process_worker
    r = call_item()
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\externals\loky\process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\apscale\b_pe_merging.py", line 29, in pe_merge
    '--threads', str(1)], stdout = output, stderr = log)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ondre\AppData\Local\Programs\Python\Python37\Scripts\apscale.exe\__main__.py", line 7, in <module>
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\apscale\__main__.py", line 50, in main
    b_pe_merging.main(args.run_apscale)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\apscale\b_pe_merging.py", line 82, in main
    Parallel(n_jobs = cores)(delayed(pe_merge)(pair, project = project, comp_lvl = comp_lvl, maxdiffpct = maxdiffpct, maxdiffs = maxdiffs, minovlen = minovlen) for pair in pairs)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 1056, in __call__
    self.retrieve()
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 435, in result
    return self.__get_result()
  File "c:\users\ondre\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
TypeError: argument of type 'WindowsPath' is not iterable
`

**Comment by DominikBuchner** [comment] 2022-09-10 18:04
Files work fine on my machine, so those are not the issue. Nr of cores can also be ruled out. 

1. Please paste the output of "pip freeze" here.
2. Can you please try to use the Path argument of apscale and see if the error persists? E.g. 'apscale --pe_merging PATH_TO_PROJECT

**Comment by OndroV** [comment] 2022-09-10 18:10
OK :)

2. Yes, it persists
![image](https://user-images.githubusercontent.com/61538402/189496312-7fcdb8b0-ce4b-4909-8e0d-2224fee120a3.png)

1. 
appdirs==1.4.4
apscale==1.5.5
apscale-gui==1.1.6
backcall==0.2.0
beautifulsoup4==4.9.3
biopython==1.78
boldigger==1.5.6
bs4==0.0.1
CacheControl==0.12.6
certifi==2020.12.5
chardet==4.0.0
colorama==0.4.4
cramjam==2.5.0
cssselect==1.1.0
cutadapt==4.1
cycler==0.10.0
Cython==0.29.21
decorator==4.4.2
demultiplexer==1.1.2
distro==1.6.0
dnaio==0.8.1
et-xmlfile==1.0.1
ete3==3.1.2
fake-useragent==0.1.11
fastparquet==0.8.1
feedparser==6.0.8
fsspec==2022.3.0
hdmedians==0.14.1
html5lib==1.1
idna==2.10
importlib-metadata==2.1.1
ipython==7.20.0
ipython-genutils==0.2.0
isal==0.11.1
jdcal==1.4.1
jedi==0.18.0
joblib==1.1.0
kaleido==0.2.1
kiwisolver==1.3.1
lastversion==2.0.1
lockfile==0.12.2
luddite==1.0.2
lxml==4.6.2
matplotlib==3.3.4
matplotlib-venn==0.11.6
more-itertools==8.12.0
msgpack==1.0.2
natsort==7.1.1
networkx==2.5
numexpr==2.8.1
numpy==1.20.0
openpyxl==3.0.6
packaging==21.3
pandas==1.2.1
parse==1.19.0
parso==0.8.1
patsy==0.5.1
pickleshare==0.7.5
Pillow==8.1.0
plotly==4.14.3
prompt-toolkit==3.0.14
psutil==5.9.0
pyarrow==7.0.0
pyee==8.1.0
Pygments==2.7.4
pyparsing==2.4.7
pyppeteer==0.2.5
pyquery==1.4.3
PySimpleGUI==4.34.0
python-dateutil==2.8.1
pytz==2021.1
PyYAML==6.0
requests==2.25.1
requests-html==0.10.0
retrying==1.3.3
scikit-bio==0.5.6
scikit-learn==0.24.1
scipy==1.6.0
sgmllib3k==1.0.0
Shapely==1.7.1
six==1.15.0
soupsieve==2.1
statsmodels==0.12.2
tables==3.7.0
taxontabletools==1.4.3
threadpoolctl==2.1.0
tqdm==4.63.0
traitlets==5.0.5
urllib3==1.26.3
w3lib==1.22.0
wcwidth==0.2.5
webencodings==0.5.1
websockets==8.1
xlrd==2.0.1
XlsxWriter==3.0.3
xmltodict==0.12.0
xopen==1.5.0
zipp==3.4.0

**Comment by DominikBuchner** [comment] 2022-09-10 18:18
Whats the full path of the project you try to process? I'm a bit puzzled with this problem, but we'll find a solution.
Can you copy those files into the 3_PE_merging/data folder and run 'apscale --primer_trimming#. Don't forget to add a sequence to your settings file.

[NC1_PE.fastq.gz](https://github.com/DominikBuchner/apscale/files/9541145/NC1_PE.fastq.gz)
[Uploading Sample2_PE.fastq.gz…]()

**Comment by OndroV** [comment] 2022-09-10 18:30
The path is c:\Users\ondre\Desktop\test_apscale
Primers got trimmed, but a FileNotFoundError appeared (screenshot attached). Perhaps the missing Project_report.xlsx should have been created in the PE step...
Maybe vsearch is somehow misconfigured, while cutadapt works fine? (PE is done by vsearch, while trimming is done by cutadapt right?)
![image](https://user-images.githubusercontent.com/61538402/189496969-d1931dc4-8cb9-424a-b391-f261338267df.png)

**Comment by DominikBuchner** [comment] 2022-09-10 18:35
Okay, yes this looks like it should look. Path also should not be the issue. So far so good, no further problems.
Next step: 
Please open this file:
"c:\users\ondre\appdata\local\programs\python\python37\lib\site-packages\apscale\b_pe_merging.py"

And add 'print(pairs)' in line 74 and paste the output here. 

Something has to be wrong with the file pairs detected by apscale since the error states exactly that: Apscale tries to open file_pair[0] and file_pair[1] in the pe_merging function but for some reason those are not iterable, at last thats what the error states.

**Comment by OndroV** [comment] 2022-09-10 18:40
Great!

C:\Users\ondre>apscale --pe_merging c:\Users\ondre\Desktop\test_apscale
20:39:27: Finding all file pairs in your input. This may take a while.
20:39:27: Found 3 matching file pairs in 6 input files.
20:39:27: Starting to merge forward and reverse reads.
[['c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R1.fastq.gz', 'c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R2.fastq.gz'], ['c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample1_R1.fastq.gz', 'c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample1_R2.fastq.gz'], ['c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample2_R1.fastq.gz', 'c:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample2_R2.fastq.gz']]
joblib.externals.loky.process_executor._RemoteTraceback:
"""
(... and the error continues as before)

**Comment by DominikBuchner** [comment] 2022-09-10 18:50
Can you please try creating the apscale project diretly in "C:\test_apscal" and run the analysis again? I think I found the issue but need to be sure.

**Comment by OndroV** [comment] 2022-09-10 18:55
Sure, it gave me the same error output (only the printed path is shorter of course :)

**Comment by DominikBuchner** [comment] 2022-09-10 19:02
So for some reason I still have to find out your Paths are not importet correctly. On a windows machine the output should be:

20:56:54: Finding all file pairs in your input. This may take a while.
20:56:54: Found 3 matching file pairs in 6 input files.
20:56:54: Starting to merge forward and reverse reads.
[['C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R1.fastq.gz', 'C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R2.fastq.gz'], ['C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample1_R1.fastq.gz', 'C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample1_R2.fastq.gz'], ['C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample2_R1.fastq.gz', 'C:\\Users\\Dominik\\Desktop\\test_apscale\\2_demultiplexing\\data\\Sample2_R2.fastq.gz']]

Sine all the '\' characters need to be escaped.

Next 2 steps:
1. Could you try to run 'apscale --pe_merging C:\\Users\\ondre\\Desktop\\test_apscale'
2. Could you add a print(input) to line 69 of the code?

**Comment by OndroV** [comment] 2022-09-10 19:06
Ah yes, the double-backslash got lost also in my replies...
![image](https://user-images.githubusercontent.com/61538402/189498196-f2fd8188-6678-4239-b14d-0e6d8ce0ca3c.png)

Ok, gonna add it to line 69

**Comment by OndroV** [comment] 2022-09-10 19:10
Well:
![image](https://user-images.githubusercontent.com/61538402/189498301-3f3ded66-6b57-4bab-bad9-908a7b26e16c.png)

**Comment by DominikBuchner** [comment] 2022-09-10 19:16
This all looks fine. 

1. Can you please set the cores to use to 1
2. Can you remove both print statements from before and add 'print(file_pair)' to line 17 and then print(Path(file_pair[0]), Path(file_pair[1])) to line 18 and paste the output.

**Comment by OndroV** [comment] 2022-09-10 19:20
Ok, messages are changing...
![image](https://user-images.githubusercontent.com/61538402/189498691-5f004ac3-9ec3-4167-96dc-a92cb0d3acf9.png)

**Comment by DominikBuchner** [comment] 2022-09-10 19:30
Yes but I'm still trying to figure out how this happens. I fail to replicate this on my machine even if I use the exact same strings as you do.

Can you replace the Path(file_pair[0]) and Path(file_pair[1]) in line 22/23 with a hardcoded 
Path('C:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R1') and Path('C:\\Users\\ondre\\Desktop\\test_apscale\\2_demultiplexing\\data\\NC1_R2')

and see if the output changes?

**Comment by OndroV** [comment] 2022-09-10 19:43
Ok, it's getting messy with the single vs. double backslashes :D but here's what I got
![image](https://user-images.githubusercontent.com/61538402/189499353-2417035e-bf1f-48b4-ad63-66e6c2472c04.png)

**Comment by DominikBuchner** [comment] 2022-09-10 19:45
Can you remove the Path() around it and update the output? If this does not help I'd have to try troubleshooting via zoom / teamviewer, since this seems to be a problem specific to your setup. Can you try updating to python >3.7?

**Comment by OndroV** [comment] 2022-09-10 19:50
Fine, now i got this (I also removed the print from 17 and 18 now...)
![image](https://user-images.githubusercontent.com/61538402/189499613-e4f92c0c-241d-4360-bac5-aaef7968a197.png)

**Comment by DominikBuchner** [comment] 2022-09-10 19:52
Okay, nothing is merged now. Can you please try to update python to 3.11 and reinstall apscale to that and try to run it again? If that does not help we'd have to do it via zoom / teamviewer. From the Traceback everything looks right and I can't tell what causes the issue here.

**Comment by OndroV** [comment] 2022-09-10 20:39
... sorry, I got stuck with some dependencies. Rust and Cargo are installed, in the PATH, but not helping
![image](https://user-images.githubusercontent.com/61538402/189500977-89a879ab-4515-47b8-bbbd-87c9d045c4ce.png)

**Comment by DominikBuchner** [comment] 2022-09-10 20:46
Are you installing the dependencies via pip? I don't see why you'd need
rust or cargo for that.

Ondrej Vargovčík ***@***.***> schrieb am Sa., 10. Sept. 2022,
22:39:

**Comment by OndroV** [comment] 2022-09-10 20:50
Yes, I got that error on `pip install apscale` , then I followed the instructions, got it again, then I added the bin directories to PATH manually, got the error again. And I get it also with `pip install cramjam`

**Comment by DominikBuchner** [comment] 2022-09-10 20:53
Lets look at this via zoom / Teamviewer tomorrow, this gets way more
complicated than it should be :D.

Ondrej Vargovčík ***@***.***> schrieb am Sa., 10. Sept. 2022,
22:50:

**Comment by OndroV** [comment] 2022-09-10 21:03
Ok, thanks. I am in the field so hopefully 5pm we re back home, or around
8pm i will be ready for sure. Looking forward to solving this strange thing
:D

Dňa so 10. 9. 2022, 22:53 DominikBuchner ***@***.***>
napísal(a):

**Comment by OndroV** [comment] 2022-09-26 13:11
Not sure, what the problem was, but reinstalling python helped. I followed [the top and flagged answers here, as well as their comments](https://stackoverflow.com/questions/3515673/how-to-completely-remove-python-from-a-windows-machine) and chose a stable release this time (3.10.7)

Unfortunately, it's not the end of the story :/ 
After primer trimming, apscale was not able to set attribute 'book'
![image](https://user-images.githubusercontent.com/61538402/192284823-1028bdf1-697b-4ac3-bd5c-04a49f65ba6e.png)

**Comment by DominikBuchner** [comment] 2022-09-26 14:29
Have you tried updating openpyxl? Also have never seen this error, but looks like it fails to write the specific log for this step.. Are both reports written?

**Comment by OndroV** [comment] 2022-09-26 14:39
Tried now and openpyxl seems to have been up to date
![image](https://user-images.githubusercontent.com/61538402/192304308-0626c2c4-fa64-4b14-a900-42e6a68512ba.png)

The 'Project_report.xlsx' is flawed ...
![image](https://user-images.githubusercontent.com/61538402/192304640-6f3ef5e1-cf64-4d4c-9566-a3bb3e16878a.png)

 ... and Logfile for pooling is missing if there should be any (see the last pic in my last comment, which i edited perhaps after you commented)

**Comment by DominikBuchner** [comment] 2022-09-26 14:44
is the error reproducible?

**Closed** 2022-10-04 11:17 UTC
Labels: bug
